-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activations
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "activationCode" character varying NOT NULL,
    "userId" integer,
    "approverUserId" integer,
    "activationDate" date,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    "employeeId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(30) NOT NULL,
    surname character varying(30) NOT NULL,
    tckn character(11) NOT NULL,
    "yearOfBirth" character(4) NOT NULL,
    PRIMARY KEY ("employeeId")
);

CREATE TABLE public.employers
(
    "employerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "companyName" character varying(150) NOT NULL,
    website character varying(50) NOT NULL,
    "phoneNo" character varying(15) NOT NULL,
    PRIMARY KEY ("employerId")
);

CREATE TABLE public.jobs
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) NOT NULL,
    "employerId" integer NOT NULL,
    "positionId" integer NOT NULL,
    location character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.jobseekers
(
    "jobseekerId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(30) NOT NULL,
    surname character varying(30) NOT NULL,
    tckn character(11) NOT NULL,
    "yearOfBirth" character(4) NOT NULL,
    PRIMARY KEY ("jobseekerId")
);

CREATE TABLE public.positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying(30) NOT NULL,
    password character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activations
    ADD FOREIGN KEY ("approverUserId")
    REFERENCES public.employees ("employeeId")
    NOT VALID;


ALTER TABLE public.activations
    ADD FOREIGN KEY ("userId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY ("employeeId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY ("employerId")
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY ("employerId")
    REFERENCES public.employers ("employerId")
    NOT VALID;


ALTER TABLE public.jobs
    ADD FOREIGN KEY ("positionId")
    REFERENCES public.positions (id)
    NOT VALID;


ALTER TABLE public.jobseekers
    ADD FOREIGN KEY ("jobseekerId")
    REFERENCES public.users (id)
    NOT VALID;

END;